### PR TITLE
Support Angular 2.3

### LINKED ISSUE #36: Support angular 2.3.0?
Looks like thinks are broken with Angular 2.3.0...
```
TypeError: this._appRef.registerChangeDetector is not a function
    at DomPortalHost.attachComponentPortal (dom-portal-host.js:41)
    at DomPortalHost.BasePortalHost.attach (portal.js:128)
    at OverlayRef.attach (overlay-ref.js:12)
    at ToastrService._buildNotification (toastr-service.js:111)
    at ToastrService.error (toastr-service.js:21)
...
```
Need to use attachView now?
http://stackoverflow.com/questions/39857222/angular2-dynamic-component-injection-in-root

### PR DESCRIPTION
**Pull request by cmckni3**
Fixes #36

### CODE REVIEW

**Comment by cmckni3** [comment]
I am working on upgrading the project to Angular 2.3 as well if that's ok.

Should have a PR for it shortly.

**Comment by cmckni3** [comment]
I ended up adding the changes to this commit. I think it makes more since otherwise the build wouldn't work unless the 2.3 change was merged first.

**Comment by yarrgh** [comment]
While this fixes the issue with angular 2.3, there's still issues with angular-cli. This PR reverts back to angular-cli beta.21 which only works if you are not targeting AoT. If you try running `ng serve --aot` the issue with angular-cli comes back.

We have 2 choices:
* Merge this PR and only support angular-cli beta.21 until they release a fix
* Wait to merge this PR and only support angular < 2.3 until angular-cli releases a fix.

I'm OK with either choice. We'll just have to specify which versions of angular and angular-cli we will support until this gets resolved.

**Comment by cmckni3** [comment]
I am leaning more towards option 1 since there's no timeline on angular-cli supporting Angular 2.3.

**Comment by scttcper** [comment]
Lets meet in the middle and publish this under the next tag on npm. Let me pull this and test out your changes first.

**Comment by scttcper** [comment]
released under `npm i toastr-ng2@next`

**Comment by scttcper** [comment]
angular cli now supports it. Released under toastr-ng2@latest.

**Comment by cmckni3** [comment]
Haha. That's some timing 🍻

**Pull request merged**
